const favoritesTypes = {
    ADD_FAVORITE: 'ADD_FAVORITE',
    REMOVE_FAVORITE: 'REMOVE_FAVORITE',
    FETCH_FAVORITES_WEATHER_SUCCESS: ' FETCH_FAVORITES_WEATHER_SUCCESS',
    SET_FETCH_ERR: 'SET_FETCH_ERR'
}

export default favoritesTypes;