const currentWeatherTypes = {
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY',
    FETCH_FORECAST_SUCCESS: 'FETCH_FORECAST_SUCCESS',
    SET_FETCH_ERR: 'SET_FETCH_ERR',
}

export default currentWeatherTypes;