const currentWeatherTypes = {
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY',
    FETCH_FORECAST_SUCCESS: 'FETCH_FORECAST_SUCCESS',
    FETCH_FORECAST_FAILURE: 'FETCH_FORECAST_FAILURE',
    SET_IS_FETCHING: 'SET_IS_FETCHING'

}

export default currentWeatherTypes;