const currentWeatherTypes = {
    FETCH_WEATHER_SUCCESS: 'FETCH_WEATHER_SUCCESS',
    FETCH_WEATHER_FAILURE: 'FETCH_WEATHER_FAILURE',
    SET_CURRENT_CITY: 'SET_CURRENT_CITY'
}

export default currentWeatherTypes;